// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw-PQpoT7X1Ds429IT9SZiAZ0f-rWbm-8',
    appId: '1:1099359424912:web:e6a437fa8d13ec9ae6a315',
    messagingSenderId: '1099359424912',
    projectId: 'bookany',
    authDomain: 'bookany-2a548.firebaseapp.com',
    storageBucket: 'bookany.appspot.com',
    measurementId: 'G-YP3M9TZ0B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDbJfa_QC8QnHs6SYIkUhv3Xz-9qlADYg',
    appId: '1:1099359424912:android:49a4a16a6012efe4e6a315',
    messagingSenderId: '1099359424912',
    projectId: 'bookany',
    storageBucket: 'bookany.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADREC4-IaVqly1q1Wt5LkOTGa3xwwT8Ss',
    appId: '1:1099359424912:ios:d56cdd0ad9ad7ccee6a315',
    messagingSenderId: '1099359424912',
    projectId: 'bookany',
    storageBucket: 'bookany.appspot.com',
    iosClientId: '1099359424912-odmstdiitiqke906s42gumqdg523dhj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.practise1',
  );
}
