import 'package:json_annotation/json_annotation.dart';

import '../nearby_places_model/place_category_model.dart';

part 'hotel_search_model.g.dart'; // This file will be generated by build_runner

@JsonSerializable()
class HotelSearchModel {
  @JsonKey(name: 'hotelImages')
  List<String> hotelImages;

  @JsonKey(name: 'hotelLocationDetails')
  PlaceCategoryModel hotelLocationDetails;

  @JsonKey(name: 'highlights')
  List<String> highlights;

  @JsonKey(name: 'price')
  int price;

  @JsonKey(name: 'discountedPrice')
  int discountedPrice;

  @JsonKey(name: 'averageRatings')
  double averageRatings;

  @JsonKey(name: 'noOfRatings')
  int noOfRatings;

  @JsonKey(name: 'hotelId')
  String hotelId;

  HotelSearchModel({
    required this.hotelImages,
    required this.hotelLocationDetails,
    required this.highlights,
    required this.price,
    required this.discountedPrice,
    required this.averageRatings,
    required this.noOfRatings,
    required this.hotelId,
  });

  // Add the factory constructor for parsing from JSON
  factory HotelSearchModel.fromJson(Map<String, dynamic> json) => _$HotelSearchModelFromJson(json);

  // Add the method for serialization to JSON
  Map<String, dynamic> toJson() => _$HotelSearchModelToJson(this);
}
